package com.example.testapplication;

/**
 * Randomized Portion Generator based on percentile of dog weight
 */
public class PortionGenerator {
    // arrays half-generated by ChatGPT
    private final static String[] measurements = {
            "Quart", "Pound", "Pint", "Cup", "Ounce"
    };
    private final static String[] adjectives = {
            "savory", "sweet", "salty", "bitter", "sour", "umami", "rich", "creamy", "buttery", "cheesy", "tangy", "zesty", "spicy", "mild", "bland", "flavorful", "aromatic", "fragrant", "pungent", "smoky", "charred", "grilled", "roasted", "baked", "fried", "crispy", "crunchy", "flaky", "tender", "juicy", "succulent", "moist", "dry", "chewy", "gooey", "sticky", "silky", "velvety", "smooth", "chunky", "hearty", "filling", "light", "refreshing", "cooling", "warming", "comforting", "satisfying", "decadent", "indulgent", "luscious", "mouthwatering", "appetizing", "delectable", "divine", "heavenly", "irresistible", "vibrant", "fresh", "ripe", "overripe", "fermented", "pickled", "cured", "aged", "raw", "natural", "organic", "wholesome", "nutritious", "greasy", "oily", "fatty", "lean", "dense", "airy", "fluffy", "spongy", "delicate", "bold", "robust", "intense", "subtle", "balanced", "overpowering", "sharp", "mellow", "earthy", "nutty", "herbal", "floral", "citrusy", "garlicky", "oniony", "peppery", "sweet-and-sour", "bittersweet", "caramelized", "toasted", "burnt", "undercooked", "overcooked", "perfectly-cooked", "al dente", "velutinous", "crumbly", "powdery", "grainy", "pasty", "fibrous", "gelatinous", "glazy", "syrupy", "drizzled", "seasoned", "underseasoned", "oversalted", "well-seasoned", "complex", "layered", "simple", "classic", "traditional", "exotic", "authentic", "fusion", "gourmet", "homemade", "rustic", "elegant"
    };
    private final static String[] foods = {
        "chicken", "beef", "turkey", "lamb", "pork", "salmon", "tuna", "sardines", "chicken breast", "chicken thigh", "chicken liver", "chicken heart", "chicken gizzard", "beef liver", "beef heart", "beef kidney", "beef lung", "beef tripe", "turkey neck", "turkey liver", "turkey heart", "lamb liver", "lamb heart", "lamb kidney", "pork liver", "pork heart", "duck", "duck liver", "duck neck", "rabbit", "rabbit liver", "eggs", "scrambled eggs", "boiled eggs", "plain yogurt", "cottage cheese", "rice", "brown rice", "oatmeal", "sweet potato", "potato", "carrots", "peas", "green beans", "pumpkin", "apple slices", "blueberries", "bananas", "watermelon", "bone broth", "fish oil", "peanut butter", "dog kibble", "wet dog food", "raw dog food", "chicken feet", "beef marrow bones", "lamb bones", "dehydrated liver treats", "jerky treats"
    };
    private final static String[] times = {
            "once every month", "once every 3 weeks", "once every 2 weeks", "4 times a month", "3 times a month", "twice a month", "once a week", "twice a week", "3 times a week", "4 times a week", "5 times a week", "6 times a week", "every other week", "once every 6 days", "once every 5 days", "once every 4 days", "once every 3 days", "once every 2 days", "every other day", "every day", "once a day", "every morning", "every afternoon", "every evening", "every night", "morning and night", "twice a day", "every 12 hours", "3 times a day", "every 8 hours", "4 times a day", "every 6 hours", "5 times a day", "every 4 hours", "6 times a day", "every 3 hours", "7 times a day", "every 2 hours", "every few hours"
    };

    /**
     * returns string representation of a portion size in format
     * # (measurement) of (adjective) (food) (times)
     * @return string representation of a portion size in format
     */
    public static String getPortion(){
        return getPortion(Math.random());
    }

    /**
     * returns string representation of a portion size in format, based on percentile
     * (amount) of (adjective) (food) (times)
     * @param percentile
     * @return string representation of a portion size
     */
    public static String getPortion(double percentile){
        assert (percentile>=0)&&(percentile<=1) : "percentile must be between 0 and 1";
        double abundance = 1-percentile;
        int measurementType = (int)(Math.random()*measurements.length);
        int amount = (int)(Math.pow(2, measurementType + 1)*abundance+1);
        String measurement = measurements[measurementType];
        // adds an s to the blank measurement if the int amount is greater than 1
        if (amount>1){
            measurement += "s";
        }
        String adjective = adjectives[(int)(Math.random()*adjectives.length)];
        String food = foods[(int)(Math.random()*foods.length)];
        String time = times[(int)((1-abundance)*times.length)];
        return amount + " " + measurement + " of " + adjective + " " + food + " " + time;
    }
}
